package TasteProfile;


/**
* TasteProfile/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Tuesday, September 24, 2019 8:02:27 PM CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users */
  int getTimesPlayed (String song_id);

  /* Returns how many times a given song was played by a given user */
  int getTimesPlayedByUser (String user_id, String song_id);

  /* Returns the top 3 users by song */
  TasteProfile.TopThreeUsers getTopThreeUsersBySong (String song_id);

  /* Return the top 3 songs by user */
  TasteProfile.TopThreeSongs getTopThreeSongsByUser (String user_id);

  /* Returns the user song profile */
  TasteProfile.UserProfile getUserProfile (String user_id);
} // interface ProfilerOperations
