package TasteProfile;


import Server.SongCounterImpl;

/**
* TasteProfile/SongCounterDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Saturday, September 14, 2019 4:20:22 PM CEST
*/

public class SongCounterDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new SongCounterImpl());
  }
}
