package TasteProfile;


import Server.UserCounterImpl;

/**
* TasteProfile/UserCounterDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* Friday, September 20, 2019 6:25:05 PM CEST
*/

public class UserCounterDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new UserCounterImpl());
  }
}
